-- Catalogo de lancamento: 210 missoes (120 diarias + 90 semanais) para a rotacao (051).
-- Todas usam tipos contados no servidor (048/050). Metas respeitam os tetos anti-farm diarios
-- (ex: Waves ate 100/dia, comentarios ate 50/dia). Publico:
--   new     = primeiros 7 dias (metas baixas, nada que dependa de ja ter audiencia)
--   active  = pessoa ja ativa
--   creator = 1.000+ fas ou 30+ publicacoes (metas altas, missoes de audiencia)
--   all     = qualquer fase
-- Missao semanal concluida tambem libera +1 convite (invite_slot_reward, 050).

insert into public.mission_definitions (
  slug, title, description, mission_type, cadence, target_value, xp_reward, coin_reward,
  audience, in_rotation, invite_slot_reward, metadata
)
select
  catalog.slug,
  catalog.title,
  catalog.description,
  catalog.mission_type,
  catalog.cadence,
  catalog.target_value,
  catalog.xp_reward,
  catalog.coin_reward,
  catalog.audience,
  true,
  case when catalog.cadence = 'weekly' then 1 else 0 end,
  '{"catalog":"launch_v1"}'::jsonb
from (values
  -- ===================== DIARIAS (120) =====================
  -- Posts (12)
  ('d_post_01', 'Primeiros passos', 'Publique 1 post se apresentando para a Fluxo.', 'create_post', 'daily', 1, 50, 5, 'new'),
  ('d_post_02', 'Bom dia, Fluxo', 'Publique 1 post contando como começou seu dia.', 'create_post', 'daily', 1, 40, 4, 'all'),
  ('d_post_03', 'Opinião sincera', 'Publique 1 post com sua opinião sobre algo que está em alta.', 'create_post', 'daily', 1, 45, 4, 'all'),
  ('d_post_04', 'Dupla do dia', 'Publique 2 posts hoje.', 'create_post', 'daily', 2, 70, 6, 'all'),
  ('d_post_05', 'Recomendação quente', 'Publique 1 post recomendando uma música, série ou lugar.', 'create_post', 'daily', 1, 45, 4, 'all'),
  ('d_post_06', 'Pergunta pra galera', 'Publique 1 post com uma pergunta para seus fãs.', 'create_post', 'daily', 1, 45, 4, 'active'),
  ('d_post_07', 'Trinca de posts', 'Publique 3 posts hoje.', 'create_post', 'daily', 3, 100, 9, 'active'),
  ('d_post_08', 'Diário do flow', 'Publique 2 posts contando moments do seu dia.', 'create_post', 'daily', 2, 70, 6, 'active'),
  ('d_post_09', 'Criador em ação', 'Publique 3 posts para manter seu perfil movimentado.', 'create_post', 'daily', 3, 110, 10, 'creator'),
  ('d_post_10', 'Bastidores', 'Publique 1 post mostrando os bastidores do que você faz.', 'create_post', 'daily', 1, 50, 5, 'creator'),
  ('d_post_11', 'Hot take', 'Publique 1 post com uma opinião que vai render conversa.', 'create_post', 'daily', 1, 50, 5, 'active'),
  ('d_post_12', 'Primeira palavra', 'Publique seu primeiro post do dia.', 'create_post', 'daily', 1, 40, 4, 'new'),
  -- Flows (10)
  ('d_flow_01', 'Solta o flow', 'Publique 1 Flow.', 'create_flow', 'daily', 1, 50, 5, 'all'),
  ('d_flow_02', 'Flow de estreia', 'Publique seu Flow do dia.', 'create_flow', 'daily', 1, 50, 5, 'new'),
  ('d_flow_03', 'Em movimento', 'Publique 2 Flows hoje.', 'create_flow', 'daily', 2, 90, 8, 'active'),
  ('d_flow_04', 'Tutorial rápido', 'Publique 1 Flow ensinando algo que você sabe fazer.', 'create_flow', 'daily', 1, 55, 5, 'all'),
  ('d_flow_05', 'Vibe do momento', 'Publique 1 Flow mostrando sua vibe de hoje.', 'create_flow', 'daily', 1, 50, 5, 'all'),
  ('d_flow_06', 'Maratona de Flows', 'Publique 3 Flows hoje.', 'create_flow', 'daily', 3, 130, 12, 'creator'),
  ('d_flow_07', 'Flow com trend', 'Publique 1 Flow entrando numa trend.', 'create_flow', 'daily', 1, 55, 5, 'active'),
  ('d_flow_08', 'Dobradinha', 'Publique 2 Flows para seus fãs.', 'create_flow', 'daily', 2, 95, 9, 'creator'),
  ('d_flow_09', 'Um dia na vida', 'Publique 1 Flow mostrando um pedaço do seu dia.', 'create_flow', 'daily', 1, 50, 5, 'all'),
  ('d_flow_10', 'Primeiro take', 'Publique 1 Flow, sem medo de errar.', 'create_flow', 'daily', 1, 50, 5, 'new'),
  -- Moments: publicacao com foto ou video (10)
  ('d_mom_01', 'Clique do dia', 'Publique 1 post com foto ou vídeo.', 'create_moments', 'daily', 1, 45, 4, 'all'),
  ('d_mom_02', 'Registro feliz', 'Publique 1 foto de algo que te fez sorrir hoje.', 'create_moments', 'daily', 1, 45, 4, 'all'),
  ('d_mom_03', 'Álbum do dia', 'Publique 2 posts com foto ou vídeo.', 'create_moments', 'daily', 2, 80, 7, 'active'),
  ('d_mom_04', 'Primeira foto', 'Publique sua primeira foto na Fluxo hoje.', 'create_moments', 'daily', 1, 45, 4, 'new'),
  ('d_mom_05', 'Look do dia', 'Publique 1 foto do seu look de hoje.', 'create_moments', 'daily', 1, 45, 4, 'all'),
  ('d_mom_06', 'Rolê registrado', 'Publique 1 foto ou vídeo do seu rolê.', 'create_moments', 'daily', 1, 45, 4, 'all'),
  ('d_mom_07', 'Galeria cheia', 'Publique 3 posts com foto ou vídeo.', 'create_moments', 'daily', 3, 115, 10, 'creator'),
  ('d_mom_08', 'Céu de hoje', 'Publique 1 foto do céu de hoje.', 'create_moments', 'daily', 1, 45, 4, 'all'),
  ('d_mom_09', 'Antes e depois', 'Publique 2 fotos mostrando uma transformação.', 'create_moments', 'daily', 2, 80, 7, 'active'),
  ('d_mom_10', 'Mesa posta', 'Publique 1 foto da sua comida favorita de hoje.', 'create_moments', 'daily', 1, 45, 4, 'all'),
  -- Dar Waves (18)
  ('d_wave_01', 'Primeiras ondas', 'Dê 3 Waves em posts de outras pessoas.', 'create_wave', 'daily', 3, 30, 3, 'new'),
  ('d_wave_02', 'Espalhando energia', 'Dê 5 Waves em posts de outras pessoas.', 'create_wave', 'daily', 5, 35, 3, 'all'),
  ('d_wave_03', 'Onda boa', 'Dê 5 Waves para dar boas-vindas ao feed.', 'create_wave', 'daily', 5, 35, 3, 'new'),
  ('d_wave_04', 'Maré alta', 'Dê 10 Waves em posts de outras pessoas.', 'create_wave', 'daily', 10, 50, 5, 'all'),
  ('d_wave_05', 'Surfista', 'Dê 10 Waves em posts que você curtiu de verdade.', 'create_wave', 'daily', 10, 50, 5, 'active'),
  ('d_wave_06', 'Tsunami de apoio', 'Dê 20 Waves em posts de outras pessoas.', 'create_wave', 'daily', 20, 80, 7, 'active'),
  ('d_wave_07', 'Radar ligado', 'Dê 8 Waves em posts de outras pessoas.', 'create_wave', 'daily', 8, 45, 4, 'all'),
  ('d_wave_08', 'Fã de carteirinha', 'Dê 15 Waves em posts de outras pessoas.', 'create_wave', 'daily', 15, 65, 6, 'active'),
  ('d_wave_09', 'Maremoto', 'Dê 25 Waves em posts de outras pessoas.', 'create_wave', 'daily', 25, 95, 9, 'creator'),
  ('d_wave_10', 'Ronda no feed', 'Dê 6 Waves em posts de outras pessoas.', 'create_wave', 'daily', 6, 40, 4, 'all'),
  ('d_wave_11', 'Curtida certeira', 'Dê 4 Waves em posts de outras pessoas.', 'create_wave', 'daily', 4, 32, 3, 'new'),
  ('d_wave_12', 'Vibrando junto', 'Dê 12 Waves em posts de outras pessoas.', 'create_wave', 'daily', 12, 55, 5, 'all'),
  ('d_wave_13', 'Onda sonora', 'Dê 7 Waves em posts de outras pessoas.', 'create_wave', 'daily', 7, 42, 4, 'all'),
  ('d_wave_14', 'Correnteza', 'Dê 18 Waves em posts de outras pessoas.', 'create_wave', 'daily', 18, 75, 7, 'active'),
  ('d_wave_15', 'Mar aberto', 'Dê 30 Waves em posts de outras pessoas.', 'create_wave', 'daily', 30, 110, 10, 'creator'),
  ('d_wave_16', 'Pequenas ondas', 'Dê 3 Waves em posts de outras pessoas.', 'create_wave', 'daily', 3, 30, 3, 'all'),
  ('d_wave_17', 'Boas-vindas em onda', 'Dê 5 Waves para receber bem a galera no feed.', 'create_wave', 'daily', 5, 35, 3, 'new'),
  ('d_wave_18', 'Onda gigante', 'Dê 40 Waves em posts de outras pessoas.', 'create_wave', 'daily', 40, 130, 12, 'creator'),
  -- Comentar (18) — comentario precisa de 5+ letras e ser em post de outra pessoa
  ('d_com_01', 'Puxa conversa', 'Comente em 1 post de outra pessoa.', 'create_comment', 'daily', 1, 35, 3, 'new'),
  ('d_com_02', 'Comentário de ouro', 'Deixe 1 comentário que faça o dia de alguém.', 'create_comment', 'daily', 1, 35, 3, 'all'),
  ('d_com_03', 'Papo reto', 'Comente em 2 posts de outras pessoas.', 'create_comment', 'daily', 2, 50, 5, 'all'),
  ('d_com_04', 'Tagarela', 'Comente em 3 posts de outras pessoas.', 'create_comment', 'daily', 3, 65, 6, 'all'),
  ('d_com_05', 'Conversa boa', 'Comente em 3 posts puxando assunto.', 'create_comment', 'daily', 3, 65, 6, 'active'),
  ('d_com_06', 'Debatedor', 'Comente em 5 posts de outras pessoas.', 'create_comment', 'daily', 5, 90, 8, 'active'),
  ('d_com_07', 'Opinião na roda', 'Comente em 2 posts dando sua opinião.', 'create_comment', 'daily', 2, 50, 5, 'new'),
  ('d_com_08', 'Elogio sincero', 'Deixe 2 comentários elogiando posts de outras pessoas.', 'create_comment', 'daily', 2, 50, 5, 'all'),
  ('d_com_09', 'Rei dos comentários', 'Comente em 8 posts de outras pessoas.', 'create_comment', 'daily', 8, 120, 11, 'creator'),
  ('d_com_10', 'Resenha', 'Comente em 4 posts de outras pessoas.', 'create_comment', 'daily', 4, 75, 7, 'active'),
  ('d_com_11', 'Voz ativa', 'Comente em 6 posts de outras pessoas.', 'create_comment', 'daily', 6, 100, 9, 'creator'),
  ('d_com_12', 'Pergunta curiosa', 'Comente em 2 posts fazendo uma pergunta ao autor.', 'create_comment', 'daily', 2, 50, 5, 'all'),
  ('d_com_13', 'Conselheiro', 'Comente em 3 posts dando uma dica.', 'create_comment', 'daily', 3, 65, 6, 'all'),
  ('d_com_14', 'Primeira resposta', 'Responda 1 post de alguém com um comentário.', 'create_comment', 'daily', 1, 35, 3, 'new'),
  ('d_com_15', 'Engajador', 'Comente em 10 posts de outras pessoas.', 'create_comment', 'daily', 10, 140, 13, 'creator'),
  ('d_com_16', 'Troca de ideia', 'Comente em 4 posts de outras pessoas.', 'create_comment', 'daily', 4, 75, 7, 'all'),
  ('d_com_17', 'Apoio nos comentários', 'Comente em 3 posts apoiando quem postou.', 'create_comment', 'daily', 3, 65, 6, 'active'),
  ('d_com_18', 'Comentarista', 'Comente em 5 posts de outras pessoas.', 'create_comment', 'daily', 5, 90, 8, 'all'),
  -- Marcar pessoas com @ (10)
  ('d_men_01', 'Chama o amigo', 'Marque 1 pessoa (@) em um post seu.', 'mention_people', 'daily', 1, 35, 3, 'new'),
  ('d_men_02', 'Marca a galera', 'Marque 2 pessoas (@) nos seus posts.', 'mention_people', 'daily', 2, 45, 4, 'all'),
  ('d_men_03', 'Bonde marcado', 'Marque 3 pessoas (@) nos seus posts.', 'mention_people', 'daily', 3, 60, 5, 'all'),
  ('d_men_04', 'Menção honrosa', 'Marque 1 pessoa (@) que merece destaque.', 'mention_people', 'daily', 1, 35, 3, 'all'),
  ('d_men_05', 'Squad completo', 'Marque 5 pessoas (@) nos seus posts.', 'mention_people', 'daily', 5, 85, 8, 'active'),
  ('d_men_06', 'Collab', 'Marque 2 criadores (@) em um post de parceria.', 'mention_people', 'daily', 2, 50, 5, 'creator'),
  ('d_men_07', 'Chamada geral', 'Marque 4 pessoas (@) nos seus posts.', 'mention_people', 'daily', 4, 70, 6, 'active'),
  ('d_men_08', 'Parceria', 'Marque 1 criador (@) com quem você quer colaborar.', 'mention_people', 'daily', 1, 40, 4, 'creator'),
  ('d_men_09', 'Te vi aqui', 'Marque 2 amigos (@) que já estão na Fluxo.', 'mention_people', 'daily', 2, 45, 4, 'new'),
  ('d_men_10', 'Rede de amigos', 'Marque 3 pessoas (@) nos seus posts.', 'mention_people', 'daily', 3, 60, 5, 'all'),
  -- Seguir pessoas (14)
  ('d_fol_01', 'Primeiro seleto', 'Siga 1 pessoa nova.', 'follow_people', 'daily', 1, 30, 3, 'new'),
  ('d_fol_02', 'Novas conexões', 'Siga 2 pessoas novas.', 'follow_people', 'daily', 2, 40, 4, 'new'),
  ('d_fol_03', 'Radar de talentos', 'Siga 3 pessoas novas.', 'follow_people', 'daily', 3, 50, 5, 'all'),
  ('d_fol_04', 'Círculo crescendo', 'Siga 5 pessoas novas.', 'follow_people', 'daily', 5, 70, 6, 'all'),
  ('d_fol_05', 'Explorador', 'Siga 3 pessoas que você encontrou explorando a Fluxo.', 'follow_people', 'daily', 3, 50, 5, 'new'),
  ('d_fol_06', 'Garimpeiro', 'Siga 5 pessoas novas.', 'follow_people', 'daily', 5, 70, 6, 'active'),
  ('d_fol_07', 'Seguindo a onda', 'Siga 2 pessoas novas.', 'follow_people', 'daily', 2, 40, 4, 'all'),
  ('d_fol_08', 'Descobridor', 'Siga 4 pessoas novas.', 'follow_people', 'daily', 4, 60, 5, 'all'),
  ('d_fol_09', 'Rede em expansão', 'Siga 8 pessoas novas.', 'follow_people', 'daily', 8, 90, 8, 'active'),
  ('d_fol_10', 'Olho vivo', 'Siga 3 pessoas novas.', 'follow_people', 'daily', 3, 50, 5, 'all'),
  ('d_fol_11', 'Conexão do dia', 'Siga 1 pessoa nova.', 'follow_people', 'daily', 1, 30, 3, 'all'),
  ('d_fol_12', 'Colecionador de flows', 'Siga 6 pessoas novas.', 'follow_people', 'daily', 6, 80, 7, 'active'),
  ('d_fol_13', 'Mente aberta', 'Siga 4 pessoas de fora da sua bolha.', 'follow_people', 'daily', 4, 60, 5, 'all'),
  ('d_fol_14', 'Networking', 'Siga 10 pessoas novas.', 'follow_people', 'daily', 10, 110, 10, 'creator'),
  -- Receber Waves (10)
  ('d_rw_01', 'Onda de volta', 'Receba 3 Waves nos seus posts.', 'receive_waves', 'daily', 3, 40, 4, 'active'),
  ('d_rw_02', 'Repercussão', 'Receba 5 Waves nos seus posts.', 'receive_waves', 'daily', 5, 50, 5, 'active'),
  ('d_rw_03', 'Bombando', 'Receba 10 Waves nos seus posts.', 'receive_waves', 'daily', 10, 75, 7, 'active'),
  ('d_rw_04', 'Viralizando', 'Receba 20 Waves nos seus posts.', 'receive_waves', 'daily', 20, 110, 10, 'creator'),
  ('d_rw_05', 'Em alta', 'Receba 30 Waves nos seus posts.', 'receive_waves', 'daily', 30, 140, 13, 'creator'),
  ('d_rw_06', 'Recebendo carinho', 'Receba 5 Waves nos seus posts.', 'receive_waves', 'daily', 5, 50, 5, 'active'),
  ('d_rw_07', 'Aplausos', 'Receba 8 Waves nos seus posts.', 'receive_waves', 'daily', 8, 65, 6, 'active'),
  ('d_rw_08', 'Hit do dia', 'Receba 50 Waves nos seus posts.', 'receive_waves', 'daily', 50, 180, 16, 'creator'),
  ('d_rw_09', 'Estrela do feed', 'Receba 15 Waves nos seus posts.', 'receive_waves', 'daily', 15, 90, 8, 'creator'),
  ('d_rw_10', 'Energia recebida', 'Receba 4 Waves nos seus posts.', 'receive_waves', 'daily', 4, 45, 4, 'active'),
  -- Receber comentarios (8)
  ('d_rc_01', 'Gerou conversa', 'Receba 1 comentário em um post seu.', 'receive_comments', 'daily', 1, 40, 4, 'active'),
  ('d_rc_02', 'Roda de conversa', 'Receba 2 comentários nos seus posts.', 'receive_comments', 'daily', 2, 55, 5, 'active'),
  ('d_rc_03', 'Assunto do dia', 'Receba 3 comentários nos seus posts.', 'receive_comments', 'daily', 3, 70, 6, 'active'),
  ('d_rc_04', 'Debate aberto', 'Receba 5 comentários nos seus posts.', 'receive_comments', 'daily', 5, 95, 9, 'creator'),
  ('d_rc_05', 'Caixa cheia', 'Receba 8 comentários nos seus posts.', 'receive_comments', 'daily', 8, 130, 12, 'creator'),
  ('d_rc_06', 'Alguém respondeu', 'Receba 1 comentário em um post seu.', 'receive_comments', 'daily', 1, 40, 4, 'active'),
  ('d_rc_07', 'Papo animado', 'Receba 4 comentários nos seus posts.', 'receive_comments', 'daily', 4, 80, 7, 'creator'),
  ('d_rc_08', 'Resenha garantida', 'Receba 10 comentários nos seus posts.', 'receive_comments', 'daily', 10, 150, 14, 'creator'),
  -- Ganhar fas (6)
  ('d_fan_01', 'Novo fã', 'Ganhe 1 fã novo hoje.', 'gain_fans', 'daily', 1, 50, 5, 'active'),
  ('d_fan_02', 'Dois fãs', 'Ganhe 2 fãs novos hoje.', 'gain_fans', 'daily', 2, 70, 6, 'active'),
  ('d_fan_03', 'Crescendo', 'Ganhe 3 fãs novos hoje.', 'gain_fans', 'daily', 3, 90, 8, 'active'),
  ('d_fan_04', 'Fã-clube', 'Ganhe 5 fãs novos hoje.', 'gain_fans', 'daily', 5, 120, 11, 'creator'),
  ('d_fan_05', 'Multidão', 'Ganhe 10 fãs novos hoje.', 'gain_fans', 'daily', 10, 170, 15, 'creator'),
  ('d_fan_06', 'Primeiro fã do dia', 'Ganhe 1 fã novo hoje.', 'gain_fans', 'daily', 1, 50, 5, 'creator'),
  -- Comunidades (4)
  ('d_comm_01', 'Ache sua tribo', 'Entre em 1 comunidade.', 'join_communities', 'daily', 1, 40, 4, 'new'),
  ('d_comm_02', 'Nova comunidade', 'Entre em 1 comunidade nova.', 'join_communities', 'daily', 1, 40, 4, 'all'),
  ('d_comm_03', 'Explorando comunidades', 'Entre em 2 comunidades.', 'join_communities', 'daily', 2, 60, 6, 'new'),
  ('d_comm_04', 'Cidadão da Fluxo', 'Entre em 2 comunidades novas.', 'join_communities', 'daily', 2, 60, 6, 'all'),

  -- ===================== SEMANAIS (90) =====================
  -- Posts (8)
  ('w_post_01', 'Semana ativa', 'Publique 5 posts nesta semana.', 'create_post', 'weekly', 5, 200, 20, 'all'),
  ('w_post_02', 'Presença constante', 'Publique 7 posts nesta semana.', 'create_post', 'weekly', 7, 260, 25, 'active'),
  ('w_post_03', 'Voz da semana', 'Publique 10 posts nesta semana.', 'create_post', 'weekly', 10, 340, 32, 'creator'),
  ('w_post_04', 'Começando forte', 'Publique 3 posts nesta semana.', 'create_post', 'weekly', 3, 150, 15, 'new'),
  ('w_post_05', 'Cronista', 'Publique 8 posts nesta semana.', 'create_post', 'weekly', 8, 290, 28, 'active'),
  ('w_post_06', 'Feed vivo', 'Publique 12 posts nesta semana.', 'create_post', 'weekly', 12, 380, 36, 'creator'),
  ('w_post_07', 'Uma por dia', 'Publique 7 posts nesta semana (que tal um por dia?).', 'create_post', 'weekly', 7, 260, 25, 'all'),
  ('w_post_08', 'Primeira semana', 'Publique 4 posts na sua primeira semana.', 'create_post', 'weekly', 4, 170, 17, 'new'),
  -- Flows (8)
  ('w_flow_01', 'Semana de Flows', 'Publique 5 Flows nesta semana.', 'create_flow', 'weekly', 5, 230, 22, 'all'),
  ('w_flow_02', 'Diretor', 'Publique 7 Flows nesta semana.', 'create_flow', 'weekly', 7, 290, 28, 'active'),
  ('w_flow_03', 'Produtora', 'Publique 10 Flows nesta semana.', 'create_flow', 'weekly', 10, 380, 36, 'creator'),
  ('w_flow_04', 'Flows de estreia', 'Publique 3 Flows nesta semana.', 'create_flow', 'weekly', 3, 170, 17, 'new'),
  ('w_flow_05', 'Série da semana', 'Publique 4 Flows sobre um mesmo tema.', 'create_flow', 'weekly', 4, 200, 20, 'all'),
  ('w_flow_06', 'Ritmo de criador', 'Publique 14 Flows nesta semana.', 'create_flow', 'weekly', 14, 460, 44, 'creator'),
  ('w_flow_07', 'Consistência', 'Publique 6 Flows nesta semana.', 'create_flow', 'weekly', 6, 260, 25, 'active'),
  ('w_flow_08', 'Cinco takes', 'Publique 5 Flows nesta semana.', 'create_flow', 'weekly', 5, 230, 22, 'all'),
  -- Moments (8)
  ('w_mom_01', 'Álbum da semana', 'Publique 5 posts com foto ou vídeo nesta semana.', 'create_moments', 'weekly', 5, 210, 20, 'all'),
  ('w_mom_02', 'Fotógrafo', 'Publique 7 posts com foto ou vídeo nesta semana.', 'create_moments', 'weekly', 7, 270, 26, 'active'),
  ('w_mom_03', 'Galeria', 'Publique 10 posts com foto ou vídeo nesta semana.', 'create_moments', 'weekly', 10, 350, 33, 'creator'),
  ('w_mom_04', 'Primeiros registros', 'Publique 3 posts com foto ou vídeo nesta semana.', 'create_moments', 'weekly', 3, 150, 15, 'new'),
  ('w_mom_05', 'Diário visual', 'Publique 7 fotos ou vídeos nesta semana (que tal um por dia?).', 'create_moments', 'weekly', 7, 270, 26, 'all'),
  ('w_mom_06', 'Portfólio', 'Publique 12 posts com foto ou vídeo nesta semana.', 'create_moments', 'weekly', 12, 400, 38, 'creator'),
  ('w_mom_07', 'Memórias', 'Publique 4 posts com foto ou vídeo nesta semana.', 'create_moments', 'weekly', 4, 180, 18, 'new'),
  ('w_mom_08', 'Registro de rolê', 'Publique 6 fotos ou vídeos dos seus rolês.', 'create_moments', 'weekly', 6, 240, 23, 'active'),
  -- Dar Waves (10)
  ('w_wave_01', 'Semana de apoio', 'Dê 30 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 30, 180, 17, 'all'),
  ('w_wave_02', 'Maré cheia', 'Dê 50 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 50, 240, 23, 'active'),
  ('w_wave_03', 'Oceano', 'Dê 100 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 100, 380, 36, 'creator'),
  ('w_wave_04', 'Primeiras marés', 'Dê 20 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 20, 150, 15, 'new'),
  ('w_wave_05', 'Onda contínua', 'Dê 40 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 40, 210, 20, 'all'),
  ('w_wave_06', 'Fã número 1', 'Dê 60 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 60, 270, 26, 'active'),
  ('w_wave_07', 'Corrente do bem', 'Dê 25 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 25, 165, 16, 'new'),
  ('w_wave_08', 'Tempestade', 'Dê 150 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 150, 480, 45, 'creator'),
  ('w_wave_09', 'Ressaca', 'Dê 80 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 80, 320, 30, 'active'),
  ('w_wave_10', 'Mergulho', 'Dê 35 Waves em posts de outras pessoas.', 'create_wave', 'weekly', 35, 195, 19, 'all'),
  -- Comentar (10)
  ('w_com_01', 'Conversador', 'Comente em 10 posts de outras pessoas.', 'create_comment', 'weekly', 10, 220, 21, 'all'),
  ('w_com_02', 'Comunidade viva', 'Comente em 15 posts de outras pessoas.', 'create_comment', 'weekly', 15, 280, 27, 'active'),
  ('w_com_03', 'Voz do feed', 'Comente em 30 posts de outras pessoas.', 'create_comment', 'weekly', 30, 440, 42, 'creator'),
  ('w_com_04', 'Primeiros papos', 'Comente em 5 posts de outras pessoas.', 'create_comment', 'weekly', 5, 160, 16, 'new'),
  ('w_com_05', 'Semana de resenha', 'Comente em 20 posts de outras pessoas.', 'create_comment', 'weekly', 20, 340, 32, 'active'),
  ('w_com_06', 'Bom de papo', 'Comente em 12 posts de outras pessoas.', 'create_comment', 'weekly', 12, 250, 24, 'all'),
  ('w_com_07', 'Presente nos comentários', 'Comente em 8 posts de outras pessoas.', 'create_comment', 'weekly', 8, 200, 19, 'new'),
  ('w_com_08', 'Anfitrião', 'Comente em 25 posts de outras pessoas.', 'create_comment', 'weekly', 25, 390, 37, 'creator'),
  ('w_com_09', 'Ouvinte', 'Comente em 10 posts respondendo o que a pessoa contou.', 'create_comment', 'weekly', 10, 220, 21, 'all'),
  ('w_com_10', 'Mestre da resenha', 'Comente em 40 posts de outras pessoas.', 'create_comment', 'weekly', 40, 520, 50, 'creator'),
  -- Marcar pessoas (6)
  ('w_men_01', 'Marcador oficial', 'Marque 5 pessoas (@) nos seus posts nesta semana.', 'mention_people', 'weekly', 5, 180, 17, 'all'),
  ('w_men_02', 'Bonde da semana', 'Marque 10 pessoas (@) nos seus posts nesta semana.', 'mention_people', 'weekly', 10, 250, 24, 'active'),
  ('w_men_03', 'Rede de collabs', 'Marque 15 pessoas (@) nos seus posts nesta semana.', 'mention_people', 'weekly', 15, 320, 30, 'creator'),
  ('w_men_04', 'Trazendo amigos', 'Marque 3 amigos (@) nos seus posts nesta semana.', 'mention_people', 'weekly', 3, 140, 14, 'new'),
  ('w_men_05', 'Chama geral', 'Marque 8 pessoas (@) nos seus posts nesta semana.', 'mention_people', 'weekly', 8, 220, 21, 'all'),
  ('w_men_06', 'Conector', 'Marque 20 pessoas (@) nos seus posts nesta semana.', 'mention_people', 'weekly', 20, 380, 36, 'creator'),
  -- Seguir pessoas (8)
  ('w_fol_01', 'Rede crescendo', 'Siga 10 pessoas novas nesta semana.', 'follow_people', 'weekly', 10, 200, 19, 'all'),
  ('w_fol_02', 'Descobertas da semana', 'Siga 15 pessoas novas nesta semana.', 'follow_people', 'weekly', 15, 250, 24, 'active'),
  ('w_fol_03', 'Explorador nato', 'Siga 5 pessoas novas nesta semana.', 'follow_people', 'weekly', 5, 150, 15, 'new'),
  ('w_fol_04', 'Caçador de talentos', 'Siga 20 pessoas novas nesta semana.', 'follow_people', 'weekly', 20, 300, 28, 'active'),
  ('w_fol_05', 'Primeiros seletos', 'Siga 8 pessoas novas nesta semana.', 'follow_people', 'weekly', 8, 180, 17, 'new'),
  ('w_fol_06', 'Sempre de olho', 'Siga 12 pessoas novas nesta semana.', 'follow_people', 'weekly', 12, 220, 21, 'all'),
  ('w_fol_07', 'Conexões de criador', 'Siga 25 pessoas novas nesta semana.', 'follow_people', 'weekly', 25, 340, 32, 'creator'),
  ('w_fol_08', 'Networking semanal', 'Siga 30 pessoas novas nesta semana.', 'follow_people', 'weekly', 30, 380, 36, 'creator'),
  -- Receber Waves (8)
  ('w_rw_01', 'Semana em alta', 'Receba 30 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 30, 250, 24, 'active'),
  ('w_rw_02', 'Repercutiu', 'Receba 50 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 50, 320, 30, 'active'),
  ('w_rw_03', 'Viral', 'Receba 100 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 100, 450, 43, 'creator'),
  ('w_rw_04', 'Fenômeno', 'Receba 200 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 200, 600, 57, 'creator'),
  ('w_rw_05', 'Carinho da galera', 'Receba 20 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 20, 210, 20, 'active'),
  ('w_rw_06', 'Reconhecido', 'Receba 75 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 75, 380, 36, 'creator'),
  ('w_rw_07', 'Retorno garantido', 'Receba 40 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 40, 290, 27, 'active'),
  ('w_rw_08', 'Hit da semana', 'Receba 150 Waves nos seus posts nesta semana.', 'receive_waves', 'weekly', 150, 520, 50, 'creator'),
  -- Receber comentarios (6)
  ('w_rc_01', 'Assunto da semana', 'Receba 5 comentários nos seus posts nesta semana.', 'receive_comments', 'weekly', 5, 230, 22, 'active'),
  ('w_rc_02', 'Caixa de comentários', 'Receba 10 comentários nos seus posts nesta semana.', 'receive_comments', 'weekly', 10, 300, 28, 'active'),
  ('w_rc_03', 'Fórum aberto', 'Receba 20 comentários nos seus posts nesta semana.', 'receive_comments', 'weekly', 20, 400, 38, 'creator'),
  ('w_rc_04', 'Conversa em alta', 'Receba 15 comentários nos seus posts nesta semana.', 'receive_comments', 'weekly', 15, 350, 33, 'creator'),
  ('w_rc_05', 'Alguém tá ouvindo', 'Receba 3 comentários nos seus posts nesta semana.', 'receive_comments', 'weekly', 3, 180, 17, 'active'),
  ('w_rc_06', 'Palco', 'Receba 30 comentários nos seus posts nesta semana.', 'receive_comments', 'weekly', 30, 500, 48, 'creator'),
  -- Ganhar fas (6)
  ('w_fan_01', 'Fã-clube em formação', 'Ganhe 5 fãs novos nesta semana.', 'gain_fans', 'weekly', 5, 280, 27, 'active'),
  ('w_fan_02', 'Base crescendo', 'Ganhe 10 fãs novos nesta semana.', 'gain_fans', 'weekly', 10, 360, 34, 'active'),
  ('w_fan_03', 'Legião', 'Ganhe 25 fãs novos nesta semana.', 'gain_fans', 'weekly', 25, 480, 46, 'creator'),
  ('w_fan_04', 'Multidão semanal', 'Ganhe 50 fãs novos nesta semana.', 'gain_fans', 'weekly', 50, 620, 60, 'creator'),
  ('w_fan_05', 'Primeiros fãs', 'Ganhe 3 fãs novos nesta semana.', 'gain_fans', 'weekly', 3, 220, 21, 'all'),
  ('w_fan_06', 'Ímã de fãs', 'Ganhe 15 fãs novos nesta semana.', 'gain_fans', 'weekly', 15, 420, 40, 'creator'),
  -- Comunidades (4)
  ('w_comm_01', 'Tribos', 'Entre em 3 comunidades nesta semana.', 'join_communities', 'weekly', 3, 180, 17, 'new'),
  ('w_comm_02', 'Cidadão das comunidades', 'Entre em 5 comunidades nesta semana.', 'join_communities', 'weekly', 5, 240, 23, 'all'),
  ('w_comm_03', 'Explorador de comunidades', 'Entre em 4 comunidades nesta semana.', 'join_communities', 'weekly', 4, 210, 20, 'all'),
  ('w_comm_04', 'Nômade', 'Entre em 7 comunidades nesta semana.', 'join_communities', 'weekly', 7, 300, 28, 'active'),
  -- Convites aceitos (4)
  ('w_inv_01', 'Traga um amigo', 'Traga 1 amigo para a Fluxo com seu convite.', 'invite_accepted', 'weekly', 1, 250, 25, 'all'),
  ('w_inv_02', 'Dupla dinâmica', 'Traga 2 amigos para a Fluxo com seu convite.', 'invite_accepted', 'weekly', 2, 350, 34, 'all'),
  ('w_inv_03', 'Bonde na Fluxo', 'Traga 3 amigos para a Fluxo com seu convite.', 'invite_accepted', 'weekly', 3, 450, 43, 'active'),
  ('w_inv_04', 'Embaixador', 'Traga 5 amigos para a Fluxo com seu convite.', 'invite_accepted', 'weekly', 5, 650, 62, 'creator'),
  -- Presenca (4)
  ('w_act_01', 'Marcando presença', 'Participe da Fluxo em 3 dias diferentes nesta semana.', 'daily_active', 'weekly', 3, 150, 15, 'new'),
  ('w_act_02', 'Quase todo dia', 'Participe da Fluxo em 5 dias diferentes nesta semana.', 'daily_active', 'weekly', 5, 220, 21, 'all'),
  ('w_act_03', 'Semana completa', 'Participe da Fluxo nos 7 dias da semana.', 'daily_active', 'weekly', 7, 320, 30, 'all'),
  ('w_act_04', 'Frequentador', 'Participe da Fluxo em 4 dias diferentes nesta semana.', 'daily_active', 'weekly', 4, 180, 17, 'all')
) as catalog(
  slug, title, description, mission_type, cadence, target_value, xp_reward, coin_reward, audience
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  mission_type = excluded.mission_type,
  cadence = excluded.cadence,
  target_value = excluded.target_value,
  xp_reward = excluded.xp_reward,
  coin_reward = excluded.coin_reward,
  audience = excluded.audience,
  in_rotation = true,
  invite_slot_reward = excluded.invite_slot_reward,
  metadata = excluded.metadata,
  is_active = true;
